# Site
repository: aMimikyu/resume-cv
favicon: images/favicon.ico

# Personal info
name: Nikos Tzianas
title: Software Developer
email: nikostzianas@protonmail.com
website: www.github.com/aMimikyu/resume-cv

# Social links
twitter_username: 
github_username:  aMimikyu
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: 
linkedin_username: nikos-tzianas
# pinterest_username: jekyll
youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Computer science student with experience working in back-end development and data engineering.
  I've built a few projects by myself and I'm now looking for an entry level position that will help me grow and learn from other experienced team members.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Certifications
more_content: | # this will include new lines to allow paragraphs
  
  - Certificate of Proficiency in English (University of Michigan)
  - Oracle Certified Associate, Java SE 8 Programmer
  - Oracle Certified Professional, Java SE 8 Programmer II

skills_content: |

  - Java
  - Python
  - Android Studio
  - SQL
  - Github/git
  - C#/Unity 
  - Unix
  - Data Science Basics

# Footer
footer_show_references: true

# Build settings
remote_theme: aMimikyu/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
